version: '3.1'
services:
  mongo:
    image: mongo:7.0-rc-jammy
    container_name: blue-spot-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"